accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
]

show/urls.py
from django.urls import path
from . import views
app_name='show'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('post/<int:post_id>/', views.detail, name='detail'),
    path('exhibition/', views.exhibition, name="exhibition"),
    path('musical/', views.musical, name='musical'),
    path('concert/', views.concert, name='concert'),
    path('classic/', views.classic, name='classic'),
    path('post/<int:post_id>/comment/', views.add_comment, name='add_comment'),
    path('comment/<int:comment_id>/edit/', views.comment_edit, name= 'comment_edit'),
    path('comment/<int:comment_id>/delete', views.comment_delete, name='comment_delete'),
    path('comment/<int:comment_id>/like/', views.post_like, name='post_like'),
    path('comment/<int:comment_id>/dislike/', views.post_dislike, name='post_dislike'),
]

showtime/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import show.views, accounts

urlpatterns = [
    path('admin/', admin.site.urls),
    path('showtime/', include('show.urls')),



    
    # path('home/',show.views.home, name='home'),
    # path('musical/home/',show.views.musical_home,name='musical_home'),
    # path('musical/home/<int:musical_id>/',show.views.musical_detail,name='musical_detail'),
    # path('exhibition/home/',show.views.exhibition_home,name='exhibition_home'),
    # path('exhibition/home/<int:exhibition_id>/',show.views.exhibition_detail,name='exhibition_detail'),
    # path('classic/home/',show.views.classic_home,name='classic_home'),
    # path('classic/home/<int:classic_id>/',show.views.classic_detail,name='classic_detail'),
    # path('concert/home/',show.views.concert_home,name='concert_home'),
    # path('concert/home/<int:concert_id>/',show.views.concert_detail,name='concert_detail'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

show/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.
#전시회는 문여닫 시간
#공연은 러닝타임
#장소(지도), 기간, 제목, 시간, 가격, 전화번호, 티켓링크 

class Category(models.Model):
    category = models.CharField(max_length=30)

    def __str__(self):

        return self.category
    
class Post(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title= models.CharField(max_length=300)
    date=models.CharField(max_length=300)
    time=models.CharField(max_length=300)
    tel=models.CharField(max_length=300)
    place1=models.CharField(max_length=300)
    place2=models.CharField(max_length=300)
    place_url=models.CharField(max_length=300)
    price=models.CharField(max_length=300)
    link=models.CharField(max_length=300)
    image = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.title
    
class Exhibition(models.Model):
    title= models.CharField(max_length=300)
    date=models.CharField(max_length=300)
    time=models.CharField(max_length=300)
    tel=models.CharField(max_length=300)
    place1=models.CharField(max_length=300)
    place2=models.CharField(max_length=300)
    place_url=models.CharField(max_length=300)
    price=models.CharField(max_length=300)
    link=models.CharField(max_length=300)
    image = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.title


class Musical(models.Model):
    title= models.CharField(max_length=300)
    date=models.CharField(max_length=300)
    time=models.CharField(max_length=300)
    tel=models.CharField(max_length=300)
    place1=models.CharField(max_length=300)
    place2=models.CharField(max_length=300)
    place_url=models.CharField(max_length=300)
    price=models.CharField(max_length=300)
    link=models.CharField(max_length=300)
    image = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.title

    

class Concert(models.Model):
    title= models.CharField(max_length=300)
    date=models.CharField(max_length=300)
    time=models.CharField(max_length=300)
    tel=models.CharField(max_length=300)
    place1=models.CharField(max_length=300)
    place2=models.CharField(max_length=300)
    place_url=models.CharField(max_length=300)
    price=models.CharField(max_length=300)
    link=models.CharField(max_length=300)
    image = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.title


class Classic(models.Model):
    title= models.CharField(max_length=300)
    date=models.CharField(max_length=300)
    time=models.CharField(max_length=300)
    tel=models.CharField(max_length=300)
    place1=models.CharField(max_length=300)
    place2=models.CharField(max_length=300)
    place_url=models.CharField(max_length=300)
    price=models.CharField(max_length=300)
    link=models.CharField(max_length=300)
    image = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey('show.Post', related_name='comments', on_delete=models.CASCADE)
    nickname = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    likes = models.ManyToManyField(User, related_name='likes')
    dislikes = models.ManyToManyField(User, related_name='dislikes')
    

    def __str__(self):
        return self.text

    @property
    def count_likes(self):
        return self.likes.count()

    @property
    def count_dislikes(self):
        return self.dislikes.count()

show/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = {'nickname', 'text'}

show/views.py
from django.shortcuts import render,get_object_or_404, redirect
from .models import Musical,Exhibition,Concert,Classic, Category, Post, Comment
from .forms import CommentForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator

def home(request):
    posts = Post.objects
    home_list=Post.objects.all()
    paginator=Paginator(home_list,12)
    page=request.GET.get('page')
    postss=paginator.get_page(page)
    return render(request, 'show/home.html', {'posts' : posts, 'postss':postss})

def detail(request, post_id):
    post_detail=get_object_or_404(Post, pk = post_id)
    form = CommentForm()
    comments = Comment.objects.filter(post=post_detail)
  
    comments = sorted(comments, key=lambda c: c.likes.count(), reverse=True)

    
    return render(request, 'show/detail.html',{'post':post_detail, 'form':form, 'comments': comments,  'exhibition':exhibition})

def exhibition(request):
    posts = Post.objects
    # category = request.GET.get('category')
    # if category == 'exhibition':
    #     exhibitions = Post.objects.filter(category=exhibition)
    # elif category == 'musical':

    # exhibition = get_object_or_404(Category, pk= 2)
    # print(exhibition)
    # exhibitions = Post.objects.filter(category=exhibition)
    # print(exhibitions)
    exhibitions = Post.objects.filter(category=2)
    return render(request, 'show/exhibition.html', {'exhibitions':exhibitions})

def musical(request):
    posts = Post.objects
    musicals = Post.objects.filter(category=1)
    return render(request, 'show/musical.html', {'musicals' : musicals })

def concert(request):
    posts = Post.objects
    concerts = Post.objects.filter(category=3)
    return render(request, 'show/concert.html', {'concerts' : concerts})

def classic(request):
    posts= Post.objects
    classics = Post.objects.filter(category=4)
    return render(request, 'show/classic.html', {'classics' : classics})

def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
    return redirect('show:detail', post_id=post.pk)

def comment_edit(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.save()
            return redirect('show:detail', post_id = comment.post.id)
    else:
        form = CommentForm(instance = comment)

    return render(request, 'show/comment_edit.html', {'form' : form})

def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    post = comment.post
    comment.delete()
    return redirect('show:detail', post_id=post.id)

def post_like(request, comment_id ) :
    # 코멘트 정보 받아옴
    comment = get_object_or_404(Comment, pk=comment_id)
    post = comment.post
    print(post.comments.all)
    
    if not request.user.is_active:
        return redirect('show:detail', post_id=post.id)    

    #사용자 정보 받아옴
    user = User.objects.get(username=request.user)
    comment.likes.add(user)
    # print(comment.likes.filter(id=user.id).exists())
    # print(comment.likes.count())
    
    count = comment.likes.count()

    # print(Comment.objects.filter(like=request.user.id).exists())
    if comment.likes == user: # 이 댓글에 지금 로그인한 사용자가 좋아요 누른 적 있으면
        print(aa)

    #좋아요에 사용자가 존재하면
    # if comment.likes.filter(id = request.user.id).exists():
        # 사용자를 지움
        # comment.likes.remove(user)
    # else:
    #     # 아니면 사용자를 추가
    #     comment.likes.add(user)
    #포스트로 리디렉션
    return redirect('show:detail', post_id=post.id)
     #우리는 코멘트를 가져와서 거기다가 좋아요 기능을 만들건데
    # 코멘트마다 뭐를 하나씩 클릭하면
    # 코멘트 밑에 있는 숫자가 올라가겠끔만 하면 됨!!!


def post_dislike(request, comment_id):
        # 코멘트 정보 받아옴
        comment = get_object_or_404(Comment, pk=comment_id)
        post = comment.post
        print(post.comments.all)
        
        if not request.user.is_active:
            return redirect('shwo:detail', post_id=post.id)    
    
        #사용자 정보 받아옴
        user = User.objects.get(username=request.user)
    
        comment.dislikes.add(user)
        # print(comment.likes.filter(id=user.id).exists())
        # print(comment.likes.count())
        
    
        count = comment.dislikes.count()
    
        # print(Comment.objects.filter(like=request.user.id).exists())
        if comment.dislikes == user: # 이 댓글에 지금 로그인한 사용자가 좋아요 누른 적 있으면
            print(aa)
    
        #좋아요에 사용자가 존재하면
        # if comment.likes.filter(id = request.user.id).exists():
            # 사용자를 지움
            # comment.likes.remove(user)
        # else:
        #     # 아니면 사용자를 추가
        #     comment.likes.add(user)
        #포스트로 리디렉션
        return redirect('show:detail', post_id=post.id)
            #우리는 코멘트를 가져와서 거기다가 좋아요 기능을 만들건데
        # 코멘트마다 뭐를 하나씩 클릭하면
        # 코멘트 밑에 있는 숫자가 올라가겠끔만 하면 됨!!!

templates/show/base.html
{% load static %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>
    <link href="https://fonts.googleapis.com/css?family=Do+Hyeon&display=swap^1" rel="stylesheet">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <title>ShowTime</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'show/home.css' %}" rel="stylesheet" type="text/css">

   
</head>
<!--head end-->

<body>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <div class="d-flex" id="wrapper">

        <!-- Sidebar -->
        <div style="background-color: #78C2AD" id="sidebar-wrapper">
            <div class="sidebar-heading"><strong>ShowTime</strong></div>
            <div class="list-group list-group-flush" >
                <a href="{% url 'show:exhibition' %}" class="list-group-item list-group-item-action"style="background-color: #78C2AD">Exhibition</a>
                <a href="{% url 'show:classic' %}" class="list-group-item list-group-item-action" style="background-color: #78C2AD">Classic</a>
                <a href="{% url 'show:musical' %}" class="list-group-item list-group-item-action" style="background-color: #78C2AD">Musical/Theater</a>
                <a href="{% url 'show:concert' %}" class="list-group-item list-group-item-action" style="background-color: #78C2AD">Concert</a>
            </div>
        </div>
        <!-- /#sidebar-wrapper -->
        <!-- Page Content -->
        <div id="page-content-wrapper">

            <nav class="navbar navbar-expand-lg navbar-dark border-bottom" style="background-color: #78C2AD">
                <button class="myButton" id="menu-toggle">메뉴</button>

                <button class="navbar-toggler"  type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                        <li class="nav-item active">
                            {% if user.is_active %}
                            
                            <div style="margin-right: 30px;">
                                <a href="{% url 'show:home' %}"><button type="button" class="myButton">홈으로</button></a>
                                <a href="{% url 'logout' %}"><button type="button" class="myButton">로그아웃</button></a>
                            </div>
                            {% else %}
                            <div style="margin-right: 30px;">
                                <a href="{% url 'show:home' %}"><button type="button" class="myButton">홈으로</button></a>
                                <a href="{% url 'accounts:signup' %}"><button type="button" class="myButton" >회원가입</button></a>
                                <a href="{% url 'login' %}"><button type="button" class="myButton">로그인</button></a>
                            </div>
                            {% endif %}
                        
                        </li>
                    </ul>
                </div>
            </nav>
            <!--navbar end-->
            

            {% block content %}
            {% endblock %}
            <!-- /.row -->

        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->
    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
    });
    </script>

</body>

</html>

templates/show/classic.html
{% extends "show/base.html" %}

{% block content %}
  
        <div class="fluid-center" style="padding: 15px; margin: 25px;">
        <div class="row">
        {% for post in classics %}
            <div class="col-lg-3 col-md-6 mb-4">
                    <div class="card h-100">
                        {% if post.image %}
                        <a href="{% url 'detail' post.id %}"><img class="card-img-top" src="{{ post.image.url }}" alt="" height=300></a>
                        {% endif %}
                        <div class="card-body">
                            <h4 class="card-title">
                            <a href="{% url 'detail' post.id %}" style="color: green;">{{ post.title }}</a>
                            </h4>
                            <h5> {{post.category}}</h5>
                            <h5> {{post.date}}</h5>
                            <h5>{{post.place1}}</h5>
                            <p class="card-text"></p>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted"></small>
                        </div>
                    </div>
                </div>
        {% endfor %}
            </div>

        </div>
        <!-- /.row -->
        </div>
 </div>
 
{% endblock %}

templates/show/comment_edit.html
{% extends "show/base.html" %}

{% block content %}

<div class="fluid-center" style="padding: 15px; margin: 5px 120px;">
        <div class="row">
<div class="form-group">
    <h4>댓글 수정</h4>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        
        <button type="submit" class="myButton">수정하기</button>
    </form> 
</div>
</div>
</div>


{% endblock %}

templates/show/concert.html
{% extends "show/base.html" %}

{% block content %}
      <div class="fluid-center" style="padding: 15px; margin: 25px;">
        <div class="row">
        {% for post in concerts %}
            <div class="col-lg-3 col-md-6 mb-4">
                    <div class="card h-100">
                        {% if post.image %}
                        <a href="{% url 'detail' post.id %}"><img class="card-img-top" src="{{ post.image.url }}" alt="" height=300></a>
                        {% endif %}
                        <div class="card-body">
                            <h4 class="card-title">
                            <a href="{% url 'detail' post.id %}" style="color: green;">{{ post.title }}</a>
                            </h4>
                            <h5> {{post.category}}</h5>
                            <h5> {{post.date}} </h5>
                            <h5>{{post.place1}}</h5>
                            <p class="card-text"></p>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted"></small>
                        </div>
                    </div>
                </div>
        {% endfor %}
            </div>

        </div>
        <!-- /.row -->
        </div>
   </div>
{% endblock %}

templates/show/detail.html
{% extends "show/base.html" %}

{% block content %}
<div class="row">
    <div class="fluid-center" style="padding: 15px; margin: 5px 120px;">
        <div class="row">
            <div style="margin: 50px;">
                <h2>{{post_detail.title}}</h2>
                <hr>
                <table border=0 >
                    <td>
                        <img  src="{{ post.image.url }}" alt="" width=300 height=400>
                    </td>
                    <td style="padding: 30px;"></td>
                    <td style="width: 800px; padding-right: 200px">
                        <p class="detail" >
                        카테고리: {{post.category}} <br><br>
                        날짜: {{post.date}} <br><br>
                        시간: {{post.time}}<br><br>
                        전화번호: {{post.tel}}<br><br>
                        장소: <a href="{{post.place_url}}" target='_blank'>{{post.place2}}</a><br><br>
                        가격: {{post.price}}<br><br>
                        
                        <a href="{{post.link}}" target='_blank'><button >티켓예매</button></a></p>
                        
                    </td>
                </table>
            </div>
        </div>

        <hr>

        <p>댓글 {{post.comments.count}}개</p>
        <!-- 좋아요 순으로 정렬 된것이지만 숫자는 상관없음 -->

         {% for comment in comments  %}
                <div>
                    
                    <p ><strong> nickname: {{comment.nickname}}</strong></p>
                    <p >{{comment.text|linebreaks}}</p>
                    <p style="font-size: 15px;">{{comment.created_date}}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="{% url 'post_like' comment.id %}">좋아요!</a>&nbsp;{{ comment.likes.count }}
                    

                    <a href="{% url 'post_dislike' comment.id %}">싫어요!</a>&nbsp;{{ comment.dislikes.count }} </P>
                    <a href = "{% url 'comment_edit' comment.id %}" class="myButton">댓글 수정</a>
                    <a href = "{% url 'comment_delete' comment.id %}" class="myButton" onclick="return confirm('정말로 삭제하시겠습니까?')">댓글 삭제</a>
                    <br>
                    <hr>

                </div>

                <br>

                {% empty %}
                <p>댓글이 존재하지 않습니다!!!</p>
            
        {% endfor %}

        <div class="form-group">
                <h4>댓글 작성</h4>
                <form method="POST" action="{% url 'add_comment' post.id %}">
                    {% csrf_token %}
                    {{ form.as_p }}

                    <button type="submit" class="myButton">작성하기</button>
                </form> 
        </div>
    
    </div>
</div>
{% endblock %}

templates/show/exhibition.html
{% extends "show/base.html" %}

{% block content %}
      <div class="fluid-center" style="padding: 15px; margin: 25px;">
         <div class="row">
        {% for post in exhibitions %}
            <div class="col-lg-3 col-md-6 mb-4">
                    <div class="card h-100">
                        {% if post.image %}
                        <a href="{% url 'detail' post.id %}"><img class="card-img-top" src="{{ post.image.url }}" alt="" height=300></a>
                        {% endif %}
                        <div class="card-body">
                            <h4 class="card-title">
                            <a href="{% url 'detail' post.id %}" style="color: green;">{{ post.title }}</a>
                            </h4>
                            <h5> {{post.category}}</h5>
                            <h5> {{post.date}}</h5>
                            <h5>{{post.place1}}</h5>
                            <p class="card-text"></p>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted"></small>
                        </div>
                    </div>
                </div>
        {% endfor %}
            </div>

        </div>
        <!-- /.row -->
        </div>
</div>
{% endblock %}

templates/show/home.html
{% extends "show/base.html" %}

{% load static %}
{% load staticfiles %}


{% block content %}
    <div class="row">
        <div class="fluid-center" style="padding: 15px; margin: 25px; margin-left: 100px; margin-right: 100px;">
        <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
                <div class="carousel-item active">
                    <img class="d-block img-fluid" src="{% static 'p1.png' %}" alt="First slide" style="width: 100%;">
                </div>
                <div class="carousel-item">
                    <img class="d-block img-fluid" src="{% static 'p2.png' %}" alt="Second slide" style="width: 100%;">
                </div>
                <div class="carousel-item">
                    <img class="d-block img-fluid" src="{% static 'p3.png' %}" alt="Third slide" style="width: 100%;">
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>

        <div class="row">

                    {% for post in posts.all %}
                    <div class="col-lg-3 col-md-6 mb-4">
                        <div class="card h-100">
                            {% if post.image %}
                            <a href="{% url 'detail' post.id %}"><img class="card-img-top" src="{{ post.image.url }}" alt="" height=300></a>
                            {% endif %}
                            <div class="card-body">
                                <h4 class="card-title">
                                <a href="{% url 'detail' post.id %}" style="color: green;">{{ post.title }}</a>
                                </h4>
                                <h5> {{post.category}}</h5>
                                <h5> {{post.date}}</h5>
                                <h5>{{post.place1}}</h5>
                                <p class="card-text"></p>
                            </div>
                            <div class="card-footer">
                                <small class="text-muted"></small>
                            </div>
                        </div>
                    </div>
                    
                    {% endfor %}
                    <div class="row">
                        <div style="margin-left: 270px; align: right; text-align: center; position: fixed; bottom: 0;" >
                            {% if postss.has_previous %}
                            <a href="?page=1">처음</a>
                            <a href="?page={{postss.previous_page_number}}">이전</a>
                            {% endif %}

                            <span>{{postss.number}}</span>
                            <span>-</span>
                            <span>{{postss.paginator.num_pages}}</span>

                            {% if postss.has_next %}
                            <a href="?page={{postss.next_page_number}}">다음</a>
                            <a href="?page={{postss.paginator.num_pages}}">마지막</a>
                            {% endif %} 
                        </div>
                    </div>
                </div>
            </div>
        
        
        </div>
      
        <!-- /.row -->
        </div>
 
{% endblock %}

templates/show/musical.html
{% extends "show/base.html" %}

{% block content %}
   
        <div class="fluid-center" style="padding: 15px; margin: 25px;">
          <div class="row">
        {% for post in musicals %}
            <div class="col-lg-3 col-md-6 mb-4">
                    <div class="card h-100">
                        {% if post.image %}
                        <a href="{% url 'detail' post.id %}"><img class="card-img-top" src="{{ post.image.url }}" alt="" height=300></a>
                        {% endif %}
                        <div class="card-body">
                            <h4 class="card-title">
                            <a href="{% url 'detail' post.id %}" style="color: green;">{{ post.title }}</a>
                            </h4>
                            <h5>  {{post.category}}</h5>
                            <h5> {{post.date}}</h5>
                            <h5>{{post.place1}}</h5>
                            <p class="card-text"></p>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted"></small>
                        </div>
                    </div>
                </div>
        {% endfor %}
            </div>

        </div>
        <!-- /.row -->
    </div>
</div>
{% endblock %}